#!/usr/bin/env python3

import colors as c
import time as t

def prompt(question):
    print(question)
    answer =  input('> ' + c.yellow)
    print(c.reset)
    return answer

print(c.clear)
print(c.red + 'Who wll dare to cross the bridge of death must answer me 3 questions')
print(c.red + 'Ere the other side he sees')

name = prompt(c.blue + 'What is your name? ')
name = prompt(c.blue + 'What is your quest?')

if name in['Lancelot','Galahad']:
    name = prompt(c.blue + 'What is your favorite colour?') 
